### ISSUE TITLE
Modify migration for autograded assessments

### ISSUE THREAD

**Issue by weiqingtoh** [Coursemology/migration#14]
Once https://github.com/Coursemology/coursemology2/pull/1169 is merged:
- (Not sure if required) Monkey patch validation for assessment. 
- Infer that trainings are autograded and missions are not.

**Comment by allenwq** [comment]
Fixed in https://github.com/Coursemology/migration/commit/35f84e879b05ecfae905ae20b59ae4bf1aba8963
